language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-28.0.3

    - android-28

    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew test
